#ifndef ESC_STM32H743_MCU_CONF_H
#define ESC_STM32H743_MCU_CONF_H

#define ESC_MCU_CONF_NAME           "STM32H743"
#define ESC_MCU_HAS_DUAL_ADC        1
#define ESC_MCU_HAS_OPAMP           0
#define ESC_MCU_HAS_FDCAN           1
#define ESC_MCU_SHUNT_PHASES        3
#ifndef ESC_MCU_RECOMMENDED_PRODUCT
#if defined(ESC_PRODUCT_ID) && (ESC_PRODUCT_ID == 0x200)
#define ESC_MCU_RECOMMENDED_PRODUCT ESC_PRODUCT_ESC200
#else
#define ESC_MCU_RECOMMENDED_PRODUCT ESC_PRODUCT_ESC120
#endif
#endif
#define ESC_MCU_PWM_FREQ_KHZ_MAX    40.0f
#define ESC_MCU_PORT_STATUS         "stub"

#endif
